/**
 * catalog-fields.js
 *
 * Field schema for Toast Audience Studio - Targeting Studio.
 * Loaded as window.CATALOG_FIELDS, consumed by the inline script
 * in the Targeting page as `catalogFields`.
 *
 * Two sources:
 *   - source: 'association'  -> from location_association_v2 user attribute
 *   - (no source key)        -> from Primary_Locations_Catalog
 *
 * Types: 'string' | 'number' | 'boolean' | 'datetime'
 */
window.CATALOG_FIELDS = {
  // ========== ASSOCIATION FIELDS (from location_association_v2) ==========
  'is_finance_contact': { type: 'boolean', label: 'Is Finance Contact', source: 'association' },
  'is_service_contact': { type: 'boolean', label: 'Is Service Contact', source: 'association' },
  'has_account_admin_permission': { type: 'boolean', label: 'Has Account Admin Permission', source: 'association' },
  'has_sales_reporting_permission': { type: 'boolean', label: 'Has Sales Reporting Permission', source: 'association' },
  'has_labor_reporting_permission': { type: 'boolean', label: 'Has Labor Reporting Permission', source: 'association' },



  // ========== CATALOG FIELDS (from Primary_Locations_Catalog) ==========
  'account_rsm': { type: 'string', label: 'Account RSM' },
  'account_segment': { type: 'string', label: 'Account Segment' },
  'active_elo_v1_past_30_days': { type: 'boolean', label: 'Active ELO V1 Past 30 Days' },
  'ads_activation_date': { type: 'datetime', label: 'Ads Activation Date' },
  'ads_campaign_fees_most_recent_month': { type: 'number', label: 'Ads Campaign Fees Most Recent Month' },
  'ads_first_order_date': { type: 'datetime', label: 'Ads First Order Date' },
  'ads_is_adopted': { type: 'boolean', label: 'Ads Is Adopted' },
  'ads_most_recent_statement_date': { type: 'datetime', label: 'Ads Most Recent Statement Date' },
  'ads_provisioned_date': { type: 'datetime', label: 'Ads Provisioned Date' },
  'ads_purchased_date': { type: 'datetime', label: 'Ads Purchased Date' },
  'ads_service_fees_most_recent_month': { type: 'number', label: 'Ads Service Fees Most Recent Month' },
  'ads_statement_total_most_recent_month': { type: 'number', label: 'Ads Statement Total Most Recent Month' },
  'any3po_provisioned_date': { type: 'datetime', label: 'Any3PO Provisioned Date' },
  'any3po_purchased_date': { type: 'datetime', label: 'Any3PO Purchased Date' },
  'avg_check_size_last_30_days': { type: 'number', label: 'Avg Check Size Last 30 Days' },
  'avg_csat_score_last_90_days': { type: 'number', label: 'Avg CSAT Score Last 90 Days' },
  'branded_mobile_app_activation_date': { type: 'datetime', label: 'Branded Mobile App Activation Date' },
  'branded_mobile_app_first_usage_date': { type: 'datetime', label: 'Branded Mobile App First Usage Date' },
  'branded_mobile_app_purchased_date': { type: 'datetime', label: 'Branded Mobile App Purchased Date' },
  'business_unit': { type: 'string', label: 'Business Unit' },
  'cande_free_trial_abandoned': { type: 'boolean', label: 'C&E Free Trial Abandoned' },
  'cande_free_trial_start_date': { type: 'datetime', label: 'C&E Free Trial Start Date' },
  'cande_lifetime_order_count': { type: 'number', label: 'C&E Lifetime Order Count' },
  'catering_and_events_activation_date': { type: 'datetime', label: 'Catering And Events Activation Date' },
  'catering_and_events_first_order_date': { type: 'datetime', label: 'Catering And Events First Order Date' },
  'catering_and_events_last_order_type_created_date': { type: 'datetime', label: 'Catering And Events Last Order Type Created Date' },
  'catering_and_events_provisioned_date': { type: 'datetime', label: 'Catering And Events Provisioned Date' },
  'catering_and_events_purchased_date': { type: 'datetime', label: 'Catering And Events Purchased Date' },
  'catering_and_events_total_order_types': { type: 'number', label: 'Catering And Events Total Order Types' },
  'catering_and_events_transaction_count_last_30_days': { type: 'number', label: 'Catering And Events Transaction Count Last 30 Days' },
  'catering_online_ordering_activation_date': { type: 'datetime', label: 'Catering Online Ordering Activation Date' },
  'catering_online_ordering_first_order_date': { type: 'datetime', label: 'Catering Online Ordering First Order Date' },
  'catering_online_ordering_provisioned_date': { type: 'datetime', label: 'Catering Online Ordering Provisioned Date' },
  'catering_online_ordering_purchased_date': { type: 'datetime', label: 'Catering Online Ordering Purchased Date' },
  'churn_date': { type: 'datetime', label: 'Churn Date' },
  'country_code': { type: 'string', label: 'Country Code' },
  'customer_health_score_factor_1': { type: 'number', label: 'Customer Health Score Factor 1' },
  'customer_health_score_factor_2': { type: 'number', label: 'Customer Health Score Factor 2' },
  'days_with_timesheet_edits': { type: 'number', label: 'Days With Timesheet Edits' },
  'deliveroo_activation_date': { type: 'datetime', label: 'Deliveroo Activation Date' },
  'deliveroo_first_order_date': { type: 'datetime', label: 'Deliveroo First Order Date' },
  'deliveroo_is_adopted': { type: 'boolean', label: 'Deliveroo Is Adopted' },
  'deliveroo_provisioned_date': { type: 'datetime', label: 'Deliveroo Provisioned Date' },
  'deliveroo_purchased_date': { type: 'datetime', label: 'Deliveroo Purchased Date' },
  'doordash_activation_date': { type: 'datetime', label: 'DoorDash Activation Date' },
  'doordash_first_order_date': { type: 'datetime', label: 'DoorDash First Order Date' },
  'doordash_purchased_date': { type: 'datetime', label: 'DoorDash Purchased Date' },
  'fifth_cande_free_trial_order_date': { type: 'datetime', label: 'Fifth C&E Free Trial Order Date' },
  'first_cande_free_trial_order_date': { type: 'datetime', label: 'First C&E Free Trial Order Date' },
  'gc_activation_date': { type: 'datetime', label: 'GC Activation Date' },
  'gc_first_order_date': { type: 'datetime', label: 'GC First Order Date' },
  'gc_is_adopted': { type: 'boolean', label: 'GC Is Adopted' },
  'gc_provisioned_date': { type: 'datetime', label: 'GC Provisioned Date' },
  'gc_purchased_date': { type: 'datetime', label: 'GC Purchased Date' },
  'gmv_last_30_days': { type: 'number', label: 'GMV Last 30 Days' },
  'gmv_tier': { type: 'string', label: 'GMV Tier' },
  'go_live_date': { type: 'datetime', label: 'Go Live Date' },
  'gpv_last_30_days': { type: 'number', label: 'GPV Last 30 Days' },
  'grubhub_activation_date': { type: 'datetime', label: 'Grubhub Activation Date' },
  'grubhub_first_order_date': { type: 'datetime', label: 'Grubhub First Order Date' },
  'grubhub_purchased_date': { type: 'datetime', label: 'Grubhub Purchased Date' },
  'has_1_or_more_invoices_processed_past_90_days': { type: 'boolean', label: 'Has 1 Or More Invoices Processed Past 90 Days' },
  'has_3po': { type: 'boolean', label: 'Has 3PO' },
  'has_active_debit_card': { type: 'boolean', label: 'Has Active Debit Card' },
  'has_active_toast_checking_account': { type: 'boolean', label: 'Has Active Toast Checking Account' },
  'has_ads': { type: 'boolean', label: 'Has Ads' },
  'has_auto_savings_set_up': { type: 'boolean', label: 'Has Auto Savings Set Up' },
  'has_biweekly_timesheet_export': { type: 'boolean', label: 'Has Biweekly Timesheet Export' },
  'has_branded_mobile_app': { type: 'boolean', label: 'Has Branded Mobile App' },
  'has_catering_and_events': { type: 'boolean', label: 'Has Catering And Events' },
  'has_catering_menu_item': { type: 'boolean', label: 'Has Catering Menu Item' },
  'has_catering_online_ordering': { type: 'boolean', label: 'Has Catering Online Ordering' },
  'has_catering_related_dining_option': { type: 'boolean', label: 'Has Catering Related Dining Option' },
  'has_catering_related_menu_item': { type: 'boolean', label: 'Has Catering Related Menu Item' },
  'has_catering_related_revenue_center': { type: 'boolean', label: 'Has Catering Related Revenue Center' },
  'has_cbg_related_menu_item': { type: 'boolean', label: 'Has CBG Related Menu Item' },
  'has_completed_lease': { type: 'boolean', label: 'Has Completed Lease' },
  'has_deliveroo': { type: 'boolean', label: 'Has Deliveroo' },
  'has_enabled_tn_push_notifications_ever': { type: 'boolean', label: 'Has Enabled TN Push Notifications Ever' },
  'has_ever_had_toast_capital': { type: 'boolean', label: 'Has Ever Had Toast Capital' },
  'has_gc': { type: 'boolean', label: 'Has GC' },
  'has_jars_set_up': { type: 'boolean', label: 'Has Jars Set Up' },
  'has_just_eat': { type: 'boolean', label: 'Has Just Eat' },
  'has_kds': { type: 'boolean', label: 'Has KDS' },
  'has_kiosk': { type: 'boolean', label: 'Has Kiosk' },
  'has_loyalty': { type: 'boolean', label: 'Has Loyalty' },
  'has_marketing': { type: 'boolean', label: 'Has Marketing' },
  'has_onboarded_ads': { type: 'boolean', label: 'Has Onboarded Ads' },
  'has_online_ordering_pro': { type: 'boolean', label: 'Has Online Ordering Pro' },
  'has_oo': { type: 'boolean', label: 'Has OO' },
  'has_oo_menu_visible': { type: 'boolean', label: 'Has OO Menu Visible' },
  'has_open_catering_and_events_opportunity': { type: 'boolean', label: 'Has Open Catering And Events Opportunity' },
  'has_open_catering_and_events_pro_opportunity': { type: 'boolean', label: 'Has Open Catering And Events Pro Opportunity' },
  'has_open_xtrachef_upsell_opportunity': { type: 'boolean', label: 'Has Open XtraChef Upsell Opportunity' },
  'has_opt': { type: 'boolean', label: 'Has OPT' },
  'has_order_over_1k_dollars_past_7_days': { type: 'boolean', label: 'Has Order Over 1K Dollars Past 7 Days' },
  'has_order_with_google': { type: 'boolean', label: 'Has Order With Google' },
  'has_over_400_menu_items': { type: 'boolean', label: 'Has Over 400 Menu Items' },
  'has_shared_employees': { type: 'boolean', label: 'Has Shared Employees' },
  'has_skip': { type: 'boolean', label: 'Has Skip' },
  'has_tds': { type: 'boolean', label: 'Has TDS' },
  'has_toast_iq_grow': { type: 'boolean', label: 'Has Toast IQ Grow' },
  'has_toast_retail': { type: 'boolean', label: 'Has Toast Retail' },
  'has_toast_tables': { type: 'boolean', label: 'Has Toast Tables' },
  'has_toast_tables_plus': { type: 'boolean', label: 'Has Toast Tables Plus' },
  'has_toast_websites': { type: 'boolean', label: 'Has Toast Websites' },
  'has_tto': { type: 'boolean', label: 'Has TTO' },
  'has_used_instant_deposit': { type: 'boolean', label: 'Has Used Instant Deposit' },
  'has_xtrachef_ap': { type: 'boolean', label: 'Has XtraChef AP' },
  'has_xtrachef_inventory': { type: 'boolean', label: 'Has XtraChef Inventory' },
  'has_xtrachef_recipe': { type: 'boolean', label: 'Has XtraChef Recipe' },
  'in_toast_now_pilot': { type: 'boolean', label: 'In Toast Now Pilot' },
  'is_actively_surcharging': { type: 'boolean', label: 'Is Actively Surcharging' },
  'is_house_tip_share_enabled': { type: 'boolean', label: 'Is House Tip Share Enabled' },
  'is_managed': { type: 'boolean', label: 'Is Managed' },
  'just_eat_activation_date': { type: 'datetime', label: 'Just Eat Activation Date' },
  'just_eat_first_order_date': { type: 'datetime', label: 'Just Eat First Order Date' },
  'just_eat_is_adopted': { type: 'boolean', label: 'Just Eat Is Adopted' },
  'just_eat_provisioned_date': { type: 'datetime', label: 'Just Eat Provisioned Date' },
  'just_eat_purchased_date': { type: 'datetime', label: 'Just Eat Purchased Date' },
  'kds_activation_date': { type: 'datetime', label: 'KDS Activation Date' },
  'kds_is_adopted': { type: 'boolean', label: 'KDS Is Adopted' },
  'kds_provisioned_date': { type: 'datetime', label: 'KDS Provisioned Date' },
  'kds_purchased_date': { type: 'datetime', label: 'KDS Purchased Date' },
  'kiosk_activation_date': { type: 'datetime', label: 'Kiosk Activation Date' },
  'kiosk_is_adopted': { type: 'boolean', label: 'Kiosk Is Adopted' },
  'kiosk_provisioned_date': { type: 'datetime', label: 'Kiosk Provisioned Date' },
  'kiosk_purchased_date': { type: 'datetime', label: 'Kiosk Purchased Date' },
  'last_modified_timestamp': { type: 'datetime', label: 'Last Modified Timestamp' },
  'location_city': { type: 'string', label: 'Location City' },
  'location_name': { type: 'string', label: 'Location Name' },
  'location_state': { type: 'string', label: 'Location State' },
  'location_street': { type: 'string', label: 'Location Street' },
  'loyalty_activation_date': { type: 'datetime', label: 'Loyalty Activation Date' },
  'loyalty_is_adopted': { type: 'boolean', label: 'Loyalty Is Adopted' },
  'loyalty_provisioned_date': { type: 'datetime', label: 'Loyalty Provisioned Date' },
  'loyalty_purchased_date': { type: 'datetime', label: 'Loyalty Purchased Date' },
  'marketing_activation_date': { type: 'datetime', label: 'Marketing Activation Date' },
  'marketing_is_adopted': { type: 'boolean', label: 'Marketing Is Adopted' },
  'marketing_provisioned_date': { type: 'datetime', label: 'Marketing Provisioned Date' },
  'marketing_purchased_date': { type: 'datetime', label: 'Marketing Purchased Date' },
  'muo': { type: 'number', label: 'MUO' },
  'new_or_existing_restaurant': { type: 'string', label: 'New Or Existing Restaurant' },
  'number_of_tables': { type: 'number', label: 'Number Of Tables' },
  'online_orders_last_30_days': { type: 'number', label: 'Online Orders Last 30 Days' },
  'online_ordering_pro_activation_date': { type: 'datetime', label: 'Online Ordering Pro Activation Date' },
  'online_ordering_pro_first_order_date': { type: 'datetime', label: 'Online Ordering Pro First Order Date' },
  'online_ordering_pro_provisioned_date': { type: 'datetime', label: 'Online Ordering Pro Provisioned Date' },
  'online_ordering_pro_purchased_date': { type: 'datetime', label: 'Online Ordering Pro Purchased Date' },
  'oo_activation_date': { type: 'datetime', label: 'OO Activation Date' },
  'oo_first_order_date': { type: 'datetime', label: 'OO First Order Date' },
  'oo_is_adopted': { type: 'boolean', label: 'OO Is Adopted' },
  'oo_provisioned_date': { type: 'datetime', label: 'OO Provisioned Date' },
  'oo_purchased_date': { type: 'datetime', label: 'OO Purchased Date' },
  'oo_settings_task_completed': { type: 'boolean', label: 'OO Settings Task Completed' },
  'opt_activation_date': { type: 'datetime', label: 'OPT Activation Date' },
  'opt_is_adopted': { type: 'boolean', label: 'OPT Is Adopted' },
  'opt_provisioned_date': { type: 'datetime', label: 'OPT Provisioned Date' },
  'opt_purchased_date': { type: 'datetime', label: 'OPT Purchased Date' },
  'order_with_google_activation_date': { type: 'datetime', label: 'Order With Google Activation Date' },
  'order_with_google_first_order_date': { type: 'datetime', label: 'Order With Google First Order Date' },
  'order_with_google_provisioned_date': { type: 'datetime', label: 'Order With Google Provisioned Date' },
  'order_with_google_purchased_date': { type: 'datetime', label: 'Order With Google Purchased Date' },
  'parent_account_employee_count': { type: 'number', label: 'Parent Account Employee Count' },
  'percent_menu_item_with_images': { type: 'number', label: 'Percent Menu items with Images' },
  'parent_account_has_open_payroll_opportunity': { type: 'boolean', label: 'Parent Account Has Open Payroll Opportunity' },
  'parent_account_has_payroll': { type: 'boolean', label: 'Parent Account Has Payroll' },
  'parent_account_live_location_count': { type: 'number', label: 'Parent Account Live Location Count' },
  'parent_account_payroll_provisioned_date': { type: 'datetime', label: 'Parent Account Payroll Provisioned Date' },
  'payment_processing_vendor': { type: 'string', label: 'Payment Processing Vendor' },
  'products_purchased': { type: 'string', label: 'Products Purchased' },
  'red_flag_tickets_last_30_days': { type: 'number', label: 'Red Flag Tickets Last 30 Days' },
  'restaurant_service_model': { type: 'string', label: 'Restaurant Service Model' },
  'restaurant_type': { type: 'string', label: 'Restaurant Type' },
  'rma_requests_last_30_days': { type: 'number', label: 'RMA Requests Last 30 Days' },
  'rsm_email': { type: 'string', label: 'RSM Email' },
  'rsm_first_name': { type: 'string', label: 'RSM First Name' },
  'rsm_last_name': { type: 'string', label: 'RSM Last Name' },
  'skip_activation_date': { type: 'datetime', label: 'Skip Activation Date' },
  'skip_first_order_date': { type: 'datetime', label: 'Skip First Order Date' },
  'skip_is_adopted': { type: 'boolean', label: 'Skip Is Adopted' },
  'skip_provisioned_date': { type: 'datetime', label: 'Skip Provisioned Date' },
  'skip_purchased_date': { type: 'datetime', label: 'Skip Purchased Date' },
  'sling_free_trial_start_date': { type: 'datetime', label: 'Sling Free Trial Start Date' },
  'sling_premium_plan_start_date': { type: 'datetime', label: 'Sling Premium Plan Start Date' },
  'sling_subscription_tier': { type: 'string', label: 'Sling Subscription Tier' },
  'stp_purchased_date': { type: 'datetime', label: 'STP Purchased Date' },
  'tca_open_date': { type: 'datetime', label: 'TCA Open Date' },
  'tds_activation_date': { type: 'datetime', label: 'TDS Activation Date' },
  'tds_first_order_date': { type: 'datetime', label: 'TDS First Order Date' },
  'tds_is_adopted': { type: 'boolean', label: 'TDS Is Adopted' },
  'tds_orders_last_30_days': { type: 'number', label: 'TDS Orders Last 30 Days' },
  'tds_provisioned_date': { type: 'datetime', label: 'TDS Provisioned Date' },
  'tds_purchased_date': { type: 'datetime', label: 'TDS Purchased Date' },
  'tds_volume_last_30_days': { type: 'number', label: 'TDS Volume Last 30 Days' },
  'tenth_cande_free_trial_order_date': { type: 'datetime', label: 'Tenth C&E Free Trial Order Date' },
  'tickets_first_30_days': { type: 'number', label: 'Tickets First 30 Days' },
  'tickets_last_30_days': { type: 'number', label: 'Tickets Last 30 Days' },
  'tip_amount_last_30_days': { type: 'number', label: 'Tip Amount Last 30 Days' },
  'toast_capital_pre_qualified_latest_expiration_datetime': { type: 'datetime', label: 'Toast Capital Pre Qualified Latest Expiration Datetime' },
  'toast_iq_grow_provisioned_date': { type: 'datetime', label: 'Toast IQ Grow Provisioned Date' },
  'toast_iq_grow_purchased_date': { type: 'datetime', label: 'Toast IQ Grow Purchased Date' },
  'toast_now_app_downloaded_timestamp': { type: 'datetime', label: 'Toast Now App Downloaded Timestamp' },
  'toast_retail_activation_date': { type: 'datetime', label: 'Toast Retail Activation Date' },
  'toast_retail_first_order_date': { type: 'datetime', label: 'Toast Retail First Order Date' },
  'toast_retail_provisioned_date': { type: 'datetime', label: 'Toast Retail Provisioned Date' },
  'toast_retail_purchased_date': { type: 'datetime', label: 'Toast Retail Purchased Date' },
  'toast_tables_activation_date': { type: 'datetime', label: 'Toast Tables Activation Date' },
  'toast_tables_bookings_last_30_days': { type: 'number', label: 'Toast Tables Bookings Last 30 Days' },
  'toast_tables_first_booking_date': { type: 'datetime', label: 'Toast Tables First Booking Date' },
  'toast_tables_plus_activation_date': { type: 'datetime', label: 'Toast Tables Plus Activation Date' },
  'toast_tables_plus_first_booking_date': { type: 'datetime', label: 'Toast Tables Plus First Booking Date' },
  'toast_tables_plus_provisioned_date': { type: 'datetime', label: 'Toast Tables Plus Provisioned Date' },
  'toast_tables_plus_purchased_date': { type: 'datetime', label: 'Toast Tables Plus Purchased Date' },
  'toast_tables_provisioned_date': { type: 'datetime', label: 'Toast Tables Provisioned Date' },
  'toast_tables_purchased_date': { type: 'datetime', label: 'Toast Tables Purchased Date' },
  'toast_websites_activation_date': { type: 'datetime', label: 'Toast Websites Activation Date' },
  'toast_websites_provisioned_date': { type: 'datetime', label: 'Toast Websites Provisioned Date' },
  'toast_websites_purchased_date': { type: 'datetime', label: 'Toast Websites Purchased Date' },
  'toastorders_shard': { type: 'string', label: 'ToastOrders Shard' },
  'total_timesheet_edits': { type: 'number', label: 'Total Timesheet Edits' },
  'transaction_count_last_30_days': { type: 'number', label: 'Transaction Count Last 30 Days' },
  'tto_activation_date': { type: 'datetime', label: 'TTO Activation Date' },
  'tto_is_adopted': { type: 'boolean', label: 'TTO Is Adopted' },
  'tto_provisioned_date': { type: 'datetime', label: 'TTO Provisioned Date' },
  'tto_purchased_date': { type: 'datetime', label: 'TTO Purchased Date' },
  'ubereats_activation_date': { type: 'datetime', label: 'UberEats Activation Date' },
  'ubereats_first_order_date': { type: 'datetime', label: 'UberEats First Order Date' },
  'ubereats_purchased_date': { type: 'datetime', label: 'UberEats Purchased Date' },
  'users_added_last_7_days': { type: 'number', label: 'Users Added Last 7 Days' },
  'xtrachef_ap_activation_date': { type: 'datetime', label: 'XtraChef AP Activation Date' },
  'xtrachef_ap_provisioned_date': { type: 'datetime', label: 'XtraChef AP Provisioned Date' },
  'xtrachef_ap_purchased_date': { type: 'datetime', label: 'XtraChef AP Purchased Date' },
  'xtrachef_inventory_activation_date': { type: 'datetime', label: 'XtraChef Inventory Activation Date' },
  'xtrachef_inventory_provisioned_date': { type: 'datetime', label: 'XtraChef Inventory Provisioned Date' },
  'xtrachef_inventory_purchased_date': { type: 'datetime', label: 'XtraChef Inventory Purchased Date' },
  'xtrachef_recipe_activation_date': { type: 'datetime', label: 'XtraChef Recipe Activation Date' },
  'xtrachef_recipe_provisioned_date': { type: 'datetime', label: 'XtraChef Recipe Provisioned Date' },
  'xtrachef_recipe_purchased_date': { type: 'datetime', label: 'XtraChef Recipe Purchased Date' },
};